In [155]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [156]:
df = pd.read_csv(r"C:\Users\Juhi\IITB\sem2\MIC\MIC_project\bcn20000_metadata_2026-04-14.csv")

In [157]:
df.columns

Index(['isic_id', 'attribution', 'copyright_license', 'age_approx',
       'anatom_site_1', 'anatom_site_2', 'anatom_site_general',
       'anatom_site_special', 'concomitant_biopsy', 'diagnosis_1',
       'diagnosis_2', 'diagnosis_3', 'diagnosis_confirm_type', 'image_type',
       'lesion_id', 'melanocytic', 'sex'],
      dtype='str')

In [158]:
df.head()

,isic_id,attribution,copyright_license,age_approx,anatom_site_1,anatom_site_2,anatom_site_general,anatom_site_special,concomitant_biopsy,diagnosis_1,diagnosis_2,diagnosis_3,diagnosis_confirm_type,image_type,lesion_id,melanocytic,sex
0,ISIC_0053453,Hospital Clínic de Barcelona,CC-BY-NC,60.0,Trunk,Anterior trunk,anterior torso,NaN,True,Benign,Benign melanocytic proliferations,Nevus,histopathology,dermoscopic,IL_0433332,True,male
1,ISIC_0053454,Hospital Clínic de Barcelona,CC-BY-NC,55.0,Trunk,Anterior trunk,anterior torso,NaN,True,Malignant,Malignant melanocytic proliferations (Melanoma),"Melanoma, NOS",histopathology,dermoscopic,IL_8314504,True,male
2,ISIC_0053455,Hospital Clínic de Barcelona,CC-BY-NC,50.0,Lower extremity,NaN,lower extremity,NaN,True,NaN,NaN,NaN,histopathology,dermoscopic,IL_8065011,NaN,male
3,ISIC_0053456,Hospital Clínic de Barcelona,CC-BY-NC,50.0,Trunk,Anterior trunk,anterior torso,NaN,True,Malignant,Malignant melanocytic proliferations (Melanoma),"Melanoma, NOS",histopathology,dermoscopic,IL_5496448,True,female
4,ISIC_0053457,Hospital Clínic de Barcelona,CC-BY-NC,85.0,Head and neck,NaN,head/neck,NaN,True,Malignant,Malignant epidermal proliferations,"Squamous cell carcinoma, NOS",histopathology,dermoscopic,IL_7128083,False,male

In [159]:
df.diagnosis_3.value_counts()

diagnosis_3
Nevus                           5647
Melanoma, NOS                   4003
Basal cell carcinoma            3676
Seborrheic keratosis            1268
Solar or actinic keratosis      1088
Melanoma metastasis              633
Squamous cell carcinoma, NOS     559
Scar                             314
Solar lentigo                    283
Dermatofibroma                   168
Name: count, dtype: int64

In [160]:
df.diagnosis_2.value_counts()

diagnosis_2
Benign melanocytic proliferations                           5647
Malignant melanocytic proliferations (Melanoma)             4636
Malignant adnexal epithelial proliferations - Follicular    3676
Benign epidermal proliferations                             1551
Indeterminate epidermal proliferations                      1088
Malignant epidermal proliferations                           559
Benign soft tissue proliferations - Fibro-histiocytic        482
Benign soft tissue proliferations - Vascular                 151
Name: count, dtype: int64

In [161]:
# Exactly the same
# Nevus -> nv
# Basal cell carcinoma -> bcc
# Dermatofibroma -> df
# Solar or actinic keratosis -> akiec

# Selected mapping
# Melanoma, NOS -> mel
# Seborrheic keratosis -> bkl
# Get vasc from diagnostic_2

# Ignore
# Squamous cell carcinoma
# Scar

In [162]:
df.loc[
    df["diagnosis_2"] == "Benign soft tissue proliferations - Vascular",
    "diagnosis_3"
] = "Benign soft tissue proliferations - Vascular (diagnosis_2)"

In [163]:
df.diagnosis_3.value_counts()

diagnosis_3
Nevus                                                         5647
Melanoma, NOS                                                 4003
Basal cell carcinoma                                          3676
Seborrheic keratosis                                          1268
Solar or actinic keratosis                                    1088
Melanoma metastasis                                            633
Squamous cell carcinoma, NOS                                   559
Scar                                                           314
Solar lentigo                                                  283
Dermatofibroma                                                 168
Benign soft tissue proliferations - Vascular (diagnosis_2)     151
Name: count, dtype: int64

In [164]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18946 entries, 0 to 18945
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   isic_id                 18946 non-null  str
 1   attribution             18946 non-null  str
 2   copyright_license       18946 non-null  str
 3   age_approx              18825 non-null  float64
 4   anatom_site_1           17880 non-null  str
 5   anatom_site_2           7369 non-null   str
 6   anatom_site_general     18649 non-null  str
 7   anatom_site_special     769 non-null    str
 8   concomitant_biopsy      18946 non-null  bool
 9   diagnosis_1             17790 non-null  str
 10  diagnosis_2             17790 non-null  str
 11  diagnosis_3             17790 non-null  str
 12  diagnosis_confirm_type  15440 non-null  str
 13  image_type              18946 non-null  str
 14  lesion_id               18946 non-null  str
 15  melanocytic             17790 non-null  object
 16  sex                     18829 non-null  str
dtypes: bool(1), float64(1), object(1), str(14)
memory usage: 2.3+ MB

In [165]:
df.diagnosis_3.value_counts()

diagnosis_3
Nevus                                                         5647
Melanoma, NOS                                                 4003
Basal cell carcinoma                                          3676
Seborrheic keratosis                                          1268
Solar or actinic keratosis                                    1088
Melanoma metastasis                                            633
Squamous cell carcinoma, NOS                                   559
Scar                                                           314
Solar lentigo                                                  283
Dermatofibroma                                                 168
Benign soft tissue proliferations - Vascular (diagnosis_2)     151
Name: count, dtype: int64

In [166]:
df.describe(include="all")

,isic_id,attribution,copyright_license,age_approx,anatom_site_1,anatom_site_2,anatom_site_general,anatom_site_special,concomitant_biopsy,diagnosis_1,diagnosis_2,diagnosis_3,diagnosis_confirm_type,image_type,lesion_id,melanocytic,sex
count,18946,18946,18946,18825.00000,17880,7369,18649,769,18946,17790,17790,17790,15440,18946,18946,17790,18829
unique,18946,1,1,NaN,4,1,6,2,2,3,8,11,2,1,5440,2,2
top,ISIC_0053453,Hospital Clínic de Barcelona,CC-BY-NC,NaN,Trunk,Anterior trunk,anterior torso,acral palms or soles,True,Malignant,Benign melanocytic proliferations,Nevus,histopathology,dermoscopic,IL_5161836,True,male
freq,1,18946,18946,NaN,7369,7369,7369,670,14196,8871,5647,5647,14196,18946,31,10283,9840
mean,NaN,NaN,NaN,57.40664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,18.20610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,45.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,60.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,75.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,85.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [167]:
df.shape

(18946, 17)

In [168]:
# number of lesions are less and images are more
df.lesion_id.value_counts()

lesion_id
IL_5161836    31
IL_2969638    31
IL_4702939    27
IL_4163485    27
IL_9292662    26
              ..
IL_5092777     1
IL_1247431     1
IL_0449110     1
IL_5363787     1
IL_3588629     1
Name: count, Length: 5440, dtype: int64

In [169]:
df_count = df.groupby('lesion_id').count()
# number of times a lesion appears
df_count

,isic_id,attribution,copyright_license,age_approx,anatom_site_1,anatom_site_2,anatom_site_general,anatom_site_special,concomitant_biopsy,diagnosis_1,diagnosis_2,diagnosis_3,diagnosis_confirm_type,image_type,melanocytic,sex
lesion_id,,,,,,,,,,,,,,,,
IL_0000277,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1
IL_0001676,2,2,2,2,2,2,2,0,2,2,2,2,0,2,2,2
IL_0002125,2,2,2,2,0,0,2,2,2,0,0,0,2,2,0,2
IL_0014308,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2
IL_0016184,3,3,3,3,3,3,3,0,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IL_9991727,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1
IL_9993052,4,4,4,4,4,4,4,0,4,4,4,4,4,4,4,4
IL_9996337,5,5,5,5,5,0,5,0,5,5,5,5,5,5,5,5
IL_9998632,1,1,1,1,1,0,1,0,1,1,1,1,0,1,1,1
IL_9999026,6,6,6,6,6,6,6,0,6,6,6,6,6,6,6,6

In [170]:
# taking only those lesions having single count
df_count = df_count[df_count['diagnosis_3'] == 1]
df_count.reset_index(inplace=True)

In [171]:
df_count

,lesion_id,isic_id,attribution,copyright_license,age_approx,anatom_site_1,anatom_site_2,anatom_site_general,anatom_site_special,concomitant_biopsy,diagnosis_1,diagnosis_2,diagnosis_3,diagnosis_confirm_type,image_type,melanocytic,sex
0,IL_0000277,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1
1,IL_0059975,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1
2,IL_0069872,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1
3,IL_0085039,1,1,1,1,0,0,0,0,1,1,1,1,0,1,1,1
4,IL_0121933,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,IL_9985024,1,1,1,1,1,0,1,0,1,1,1,1,0,1,1,1
742,IL_9989548,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1
743,IL_9989891,1,1,1,1,1,0,1,0,1,1,1,1,0,1,1,1
744,IL_9991727,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1
745,IL_9998632,1,1,1,1,1,0,1,0,1,1,1,1,0,1,1,1

### Computing train test split

In [172]:
train,test = train_test_split(df["lesion_id"].unique(),random_state=42)

In [173]:
train

<StringArray>
['IL_5733393', 'IL_3096654', 'IL_1876389', 'IL_9367665', 'IL_9105360',
 'IL_5629866', 'IL_9665672', 'IL_3629164', 'IL_6096874', 'IL_7334395',
 ...
 'IL_1955343', 'IL_2493303', 'IL_8785558', 'IL_5414314', 'IL_6459311',
 'IL_1127006', 'IL_2965493', 'IL_0349863', 'IL_2299905', 'IL_9924333']
Length: 4080, dtype: str

In [174]:
test

<StringArray>
['IL_2459455', 'IL_4204830', 'IL_5727785', 'IL_2765340', 'IL_4713718',
 'IL_6140541', 'IL_6010077', 'IL_3560021', 'IL_8651031', 'IL_7568959',
 ...
 'IL_6023413', 'IL_4391327', 'IL_2396987', 'IL_9311888', 'IL_9570955',
 'IL_7260792', 'IL_4952338', 'IL_2857034', 'IL_0206046', 'IL_9317487']
Length: 1360, dtype: str

In [175]:
test_df = df[df['lesion_id'].isin(set(test))]

In [176]:
test_df.diagnosis_3.value_counts()

diagnosis_3
Nevus                                                         1433
Melanoma, NOS                                                  981
Basal cell carcinoma                                           888
Solar or actinic keratosis                                     304
Seborrheic keratosis                                           292
Melanoma metastasis                                            178
Squamous cell carcinoma, NOS                                   140
Solar lentigo                                                   80
Dermatofibroma                                                  68
Scar                                                            66
Benign soft tissue proliferations - Vascular (diagnosis_2)      43
Name: count, dtype: int64

In [177]:
train_df = df[df["lesion_id"].isin(set(train))]

In [178]:
train_df.shape,test_df.shape

((14168, 17), (4778, 17))

In [179]:
train_df.diagnosis_3.value_counts()

diagnosis_3
Nevus                                                         4214
Melanoma, NOS                                                 3022
Basal cell carcinoma                                          2788
Seborrheic keratosis                                           976
Solar or actinic keratosis                                     784
Melanoma metastasis                                            455
Squamous cell carcinoma, NOS                                   419
Scar                                                           248
Solar lentigo                                                  203
Benign soft tissue proliferations - Vascular (diagnosis_2)     108
Dermatofibroma                                                 100
Name: count, dtype: int64

In [180]:
df.diagnosis_3.value_counts()

diagnosis_3
Nevus                                                         5647
Melanoma, NOS                                                 4003
Basal cell carcinoma                                          3676
Seborrheic keratosis                                          1268
Solar or actinic keratosis                                    1088
Melanoma metastasis                                            633
Squamous cell carcinoma, NOS                                   559
Scar                                                           314
Solar lentigo                                                  283
Dermatofibroma                                                 168
Benign soft tissue proliferations - Vascular (diagnosis_2)     151
Name: count, dtype: int64

In [181]:
mapping = {
    # direct
    "Nevus": "nv",
    "Basal cell carcinoma": "bcc",
    "Dermatofibroma": "df",
    "Solar or actinic keratosis": "akiec",

    # selected
    "Melanoma, NOS": "mel",
    "Seborrheic keratosis": "bkl",
    "Benign soft tissue proliferations - Vascular (diagnosis_2)": "vasc"
}

In [190]:
train_df["dx"] = train_df["diagnosis_3"].map(mapping)

In [191]:
test_df["dx"] = test_df["diagnosis_3"].map(mapping)

In [189]:
train_df = train_df.copy()

In [192]:
train_df = train_df.dropna(subset=["dx"])

In [ ]:
test_df = test_df.dropna(subset=["dx"])

In [194]:
train_df

,isic_id,attribution,copyright_license,age_approx,anatom_site_1,anatom_site_2,anatom_site_general,anatom_site_special,concomitant_biopsy,diagnosis_1,diagnosis_2,diagnosis_3,diagnosis_confirm_type,image_type,lesion_id,melanocytic,sex,dx
0,ISIC_0053453,Hospital Clínic de Barcelona,CC-BY-NC,60.0,Trunk,Anterior trunk,anterior torso,NaN,True,Benign,Benign melanocytic proliferations,Nevus,histopathology,dermoscopic,IL_0433332,True,male,nv
1,ISIC_0053454,Hospital Clínic de Barcelona,CC-BY-NC,55.0,Trunk,Anterior trunk,anterior torso,NaN,True,Malignant,Malignant melanocytic proliferations (Melanoma),"Melanoma, NOS",histopathology,dermoscopic,IL_8314504,True,male,mel
3,ISIC_0053456,Hospital Clínic de Barcelona,CC-BY-NC,50.0,Trunk,Anterior trunk,anterior torso,NaN,True,Malignant,Malignant melanocytic proliferations (Melanoma),"Melanoma, NOS",histopathology,dermoscopic,IL_5496448,True,female,mel
5,ISIC_0053458,Hospital Clínic de Barcelona,CC-BY-NC,35.0,Head and neck,NaN,head/neck,NaN,True,Benign,Benign melanocytic proliferations,Nevus,histopathology,dermoscopic,IL_0908390,True,male,nv
6,ISIC_0053459,Hospital Clínic de Barcelona,CC-BY-NC,60.0,Trunk,Anterior trunk,anterior torso,NaN,True,Benign,Benign melanocytic proliferations,Nevus,histopathology,dermoscopic,IL_7455346,True,male,nv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18938,ISIC_0073247,Hospital Clínic de Barcelona,CC-BY-NC,85.0,Head and neck,NaN,head/neck,NaN,False,Malignant,Malignant adnexal epithelial proliferations - ...,Basal cell carcinoma,NaN,dermoscopic,IL_5031450,False,female,bcc
18939,ISIC_0073248,Hospital Clínic de Barcelona,CC-BY-NC,65.0,Trunk,Anterior trunk,anterior torso,NaN,True,Benign,Benign epidermal proliferations,Seborrheic keratosis,histopathology,dermoscopic,IL_9270243,False,male,bkl
18940,ISIC_0073249,Hospital Clínic de Barcelona,CC-BY-NC,70.0,Lower extremity,NaN,lower extremity,NaN,True,Malignant,Malignant melanocytic proliferations (Melanoma),"Melanoma, NOS",histopathology,dermoscopic,IL_4888325,True,male,mel
18941,ISIC_0073250,Hospital Clínic de Barcelona,CC-BY-NC,30.0,Trunk,Anterior trunk,anterior torso,NaN,False,Benign,Benign melanocytic proliferations,Nevus,NaN,dermoscopic,IL_9019520,True,female,nv
18945,ISIC_0073254,Hospital Clínic de Barcelona,CC-BY-NC,50.0,Upper extremity,NaN,upper extremity,NaN,True,Benign,Benign epidermal proliferations,Seborrheic keratosis,histopathology,dermoscopic,IL_5135481,False,male,bkl

In [195]:
train_df.dx.value_counts()

dx
nv       4214
mel      3022
bcc      2788
bkl       976
akiec     784
vasc      108
df        100
Name: count, dtype: int64

In [196]:
test_df.dx.value_counts()

dx
nv       1433
mel       981
bcc       888
akiec     304
bkl       292
df         68
vasc       43
Name: count, dtype: int64